name: build
on:
  push:
    branches:
      - master # run the action on your projects default branch

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          
      - name: Install build tools
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "build-tools;33.0.0" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.0.8775105" --sdk_root=${ANDROID_SDK_ROOT}
        
      - name: Initialize gradle
        run: |
          chmod +x /home/runner/work/photoNet/photoNet/gradlew
          gradle wrapper
        
      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: Build with Gradle
        run: |
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease --stacktrace
          
      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.0.5
        with:
          gradle-dependency-path: "app/build.gradle"
          gradle-build-module: ":app"
          gradle-build-configuration: "debugCompileClasspath"
