name: build
on:
  push:
    branches:
      - master # run the action on your projects default branch

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: List files in the repository
        run: |
          ls /home/runner/work/photoNet/photoNet/
          chmod +x /home/runner/work/photoNet/photoNet/gradlew
          
      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.0.5
        with:
          gradle-dependency-path: "app/build.gradle"
          gradle-build-module: ":app"
          gradle-build-configuration: "debugCompileClasspath"
